name: Convert Python Scripts to Jupyter Notebooks

on:
  push:
    branches:
      - main  # Specify the branch explicitly
    paths:
      - 'Training/Train-Phi3-2bit.py'
      - 'Training/Train-Phi3-4bit.py'
  workflow_dispatch:

jobs:
  convert-to-notebook:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupytext

      # Ensure Notebooks directory exists
      - name: Create Notebooks directory
        run: mkdir -p Notebooks

      # Convert Python scripts to Jupyter notebooks
      - name: Convert scripts to notebooks
        run: |
          for script in Training/Train-Phi3-2bit.py Training/Train-Phi3-4bit.py; do
            if [ -f "$script" ]; then
              notebook="Notebooks/$(basename "${script%.py}").ipynb"
              jupytext --to notebook "$script" -o "$notebook"
            fi
          done

      # Commit and push the notebooks if changes exist
      - name: Commit notebooks
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add Notebooks/*.ipynb
          if ! git diff --staged --quiet; then
            git commit -m "Convert Python scripts to Jupyter notebooks"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}