name: Convert Python Scripts to Jupyter Notebooks

on:
  paths:
      - 'Training/Train-Phi3-2bit.py'
      - 'Training/Train-Phi3-4bit.py'
  workflow_dispatch:

jobs:
  convert-to-notebook:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupytext

      # Ensure Notebooks directory exists
      - name: Create Notebooks directory
        run: |
          mkdir -p Notebooks

      # Convert Python scripts to Jupyter notebooks
      - name: Convert scripts to notebooks
        run: |
          if [ -f Training/Train-Phi3-2bit.py ]; then
            jupytext --to notebook Training/Train-Phi3-2bit.py -o Notebooks/Train-Phi3-2bit.ipynb
          fi
          if [ -f Training/Train-Phi3-4bit.py ]; then
            jupytext --to notebook Training/Train-Phi3-4bit.py -o Notebooks/Train-Phi3-4bit.ipynb
          fi

      # Commit and push the notebooks if changes exist
      - name: Commit notebooks
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Notebooks/Train-Phi3-2bit.ipynb Notebooks/Train-Phi3-4bit.ipynb
          git diff --staged --quiet || git commit -m "Convert Train-Phi3-2bit.py and Train-Phi3-4bit.py to Jupyter notebooks in Notebooks folder"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}